name = "SpeedrunPack"
author = "interp"
version = "mc1.20.4-v3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16e36752663c4d38e81ebf8e6c6a26b4c19d9f39e28715039b6a1ff5f4c2e048"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
