name = "SpeedrunPack"
author = "interp"
version = "mc25w14craftmine-v1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06387dbb43491218575d7028d2e09ce3c2f2db4a146c52c0e4757adc00ec6c1b"

[versions]
fabric = "0.16.14"
minecraft = "25w14craftmine"
