hash-format = "sha256"

[[files]]
file = "mods/atum.pw.toml"
hash = "45abe619362f9b20ebec599bf1d463488b23b9c43cccda0e169b636b2529cdf1"
metafile = true

[[files]]
file = "mods/biome_threadlocal_fix.pw.toml"
hash = "26613b50a1f9ad2f5f0156a246745e245c3a672c8a8a7690e68bec5117b0f9ea"
metafile = true

[[files]]
file = "mods/fabricproxy-lite.pw.toml"
hash = "6dfb5249a862f33e0cac5e84d4e8767fd66ccfa486e3d8b84dd7117df1adbf22"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "e0975111acc84b976b810a06165f244e5edab6db00e7a5affdd17b962f52f2d9"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "cb16723c8c5ab522cd4bd10e200b61cebc55fc0ab7eca8d76ececcd158399650"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c86cbdf63c3242264b656d892db3839f9ab585958295bb1aa3b102e6bb614eb1"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "781f6c2b36d9ead66fa78f84bc06d0816849f0fb527e447a0d0ca7e8860f0c42"
metafile = true

[[files]]
file = "mods/planifolia.pw.toml"
hash = "1a27fe495b6768f58953d3bfc82434be17449cfe875fa5fcb18fb57ee9e17928"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "c2a5d95b93c23099a6fd3e4db724b238d76707d5628b81834f40f5cb4bfe1e4c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "7c8430e316e4055c8cb5ef41bed338fc6243f4720cd41015348202c00a53594a"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "0b10a9ee9d483f6802bc060e2d0773da98a7d8c4a4f53eded91f4552bc6e04e2"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "89d513f85304ec15e18a2347a5fdc0d89d27ebef997236f61dbd06426cdbbe36"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "1b1c537637fe0379fe1a1721389cbe2033515b2ca178b8f3e71388d76a844308"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "1bb5e0306d557db0ac6c72363372f15eef8cbae55c6deb96c8d9089bc5bf8c6b"
metafile = true
