name = "SpeedrunPack"
author = "interp"
version = "mc1.20.4-v4.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f275b094497e4d8114bc2206bbeb03189416442a1781116971f3018d6a2004c"

[versions]
fabric = "0.17.2"
minecraft = "1.20.4"
