name = "SpeedrunPack"
author = "interp"
version = "mc1.17.1-v4.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e0aa231586706fac876b0f0752ea5a2a3392ead657abc8497f34069a87df6e4"

[versions]
fabric = "0.18.4"
minecraft = "1.17.1"
