hash-format = "sha256"

[[files]]
file = "mods/antiresourcereload.pw.toml"
hash = "e49405614fac145c9824b5005c092cf212d96e19ee5eccf979648d38d3c72b96"
metafile = true

[[files]]
file = "mods/atum.pw.toml"
hash = "6e35b989f44c955cf381d60a4e7ce58aac3c1657a9b702c8f83e66bf3ecd1061"
metafile = true

[[files]]
file = "mods/extra-options.pw.toml"
hash = "d34c21f035b5c8759cfb78f49ad99d12d01727494412836dfcf5cdfab224fa3c"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "c3db1444923b5eccafebf8024efbd6a16edaeb79a013c9525d1b3e8d75693c9a"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "cb16723c8c5ab522cd4bd10e200b61cebc55fc0ab7eca8d76ececcd158399650"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "79d8acc0638aff455f1c12ae8e3d4c0433314e9fd3f06f8cfc7f9de7372d532e"
metafile = true

[[files]]
file = "mods/lazystronghold.pw.toml"
hash = "e52cf61a4e29bda1ab0853f51714f115635692eea78ffa562aa34ac0a749910b"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "5e97ed3b83be24cb13ad94eae7c475bac5c4be1f75527e41268e7079d627273e"
metafile = true

[[files]]
file = "mods/speedrunapi.pw.toml"
hash = "59ccb84d2ae8f96142c0063b506199b44c764763ed29d497e56bde4cddd8f160"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "1569abcbd1ac9b699e9684c7ca7c10ef20bd7b04f7aa8c6cc27873f477b29959"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "a8ed9b02a67d4d6d85ebb6b54575338efe4392726cb7ad328958a705275ba31b"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "848706cf399e7d55911bf15bf86fdbebff51f2346a629b2ba9230056742d3a1c"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "01801d8f2e565f06b540e9f4d86e61a1112fe9e320dd848301f2dfa9138efe88"
metafile = true

[[files]]
file = "mods/voyager.pw.toml"
hash = "619642572e888cc32bd09b11bbf1dfea8240532c2847456a4300b746fc7ce8c1"
metafile = true

[[files]]
file = "mods/worldpreview.pw.toml"
hash = "a391dfa9c49688c0380843942bfdc85ce0a7d8d1e02d8cf2a1ebb5a39f85870c"
metafile = true

[[files]]
file = "mods/z-buffer-fog.pw.toml"
hash = "5c0ad9116590047a778e646d7d0b4e8874db68f786888ae9774eca22515d6b3c"
metafile = true
