name = "SpeedrunPack"
author = "interp"
version = "mc1.14.4-v4.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbf26b80d03d5d1d4c3396e5e6c98b274a07e72f1aed3ae11d5fe5d2f2131ccf"

[versions]
fabric = "0.16.2"
minecraft = "1.14.4"
