name = "SpeedrunPack"
author = "interp"
version = "mc1.14.4-v4.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06e9f1f219dda40ad6c20d12cd8f51d11975aa4a5149a07e990320a74336f50f"

[versions]
fabric = "0.18.4"
minecraft = "1.14.4"
