name = "SpeedrunPack"
author = "interp"
version = "mc1.14.4-v4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b00dfbdf612107d74565073429e69c9ee406a0e9336abbdbda095113f52d7143"

[versions]
fabric = "0.17.2"
minecraft = "1.14.4"
