name = "SpeedrunPack"
author = "interp"
version = "mc1.17.1-v4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55448b1eb0b75c9ff9ab00949d077fd34e4190e13870d8d7da02f5b317f2542c"

[versions]
fabric = "0.16.2"
minecraft = "1.17.1"
