name = "SpeedrunPack"
author = "interp"
version = "mc1.17.1-v4.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7416d949fee7e6a5e6af82625da52a10a52046cd5e506c287b6790129fdbd755"

[versions]
fabric = "0.17.3"
minecraft = "1.17.1"
