hash-format = "sha256"

[[files]]
file = "mods/atum.pw.toml"
hash = "5933544df20b83b109d8622ad4ab62732e26a8ea7697fba784fb6142c49c2993"
metafile = true

[[files]]
file = "mods/biome_threadlocal_fix.pw.toml"
hash = "beab203770a27295c5210cb2390691db6cac03c0c7d95da141b7cc306b4d9952"
metafile = true

[[files]]
file = "mods/fabricproxy-lite.pw.toml"
hash = "f9286b56143a6379ce798304766dec018bb6e411f31ba27a459eb3fbf86ce1af"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "c1b8efb448c1a748c2d6b843e4e55b3b0402a8e9bb27b39c5ce4805a80d6c289"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "cb16723c8c5ab522cd4bd10e200b61cebc55fc0ab7eca8d76ececcd158399650"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "d7a58a8ec43438e53eb25258c3489b29fa9727a5f931f256ecb2e67c742e1b8d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "bb89dca8fc1becad4d88ec01726b5a8ff94f297994b0caaf4fdc49463194e4b3"
metafile = true

[[files]]
file = "mods/planifolia.pw.toml"
hash = "3bd4a7994053062e810a255f1af8357a31b19a0bd3fbc2227491369d42eadcc9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "1272822461650c3d569a910af2f384a422860b3ade972a6f12b0eda43581afff"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "a9917b2e12c3b20de6c807b05a01688df7b570719f5b2fa4f5a45ae6b15116ab"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "9e9133b251c739610d4e06d9775811d7c22ab546e041d674e7427ac467774721"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "1bb5e0306d557db0ac6c72363372f15eef8cbae55c6deb96c8d9089bc5bf8c6b"
metafile = true
