name = "SpeedrunPack"
author = "interp"
version = "mc1.21.8-v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7a8cd4604bcc9a90c00b5c5978841a2c10573e140f8390b8ebe590bc4233e86"

[versions]
fabric = "0.16.14"
minecraft = "1.21.8"
