name = "SpeedrunPack"
author = "interp"
version = "mc1.21.8-v1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbbaab1ced047ae6a7fb67d568001beba2ea3f22cc9da7f0836688651b74ff9d"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
