hash-format = "sha256"

[[files]]
file = "mods/atum.pw.toml"
hash = "8d0c6e27a26a2e7e186c65adcdeb22aa09734118b8383c542c843dc295202ec7"
metafile = true

[[files]]
file = "mods/biome_threadlocal_fix.pw.toml"
hash = "26613b50a1f9ad2f5f0156a246745e245c3a672c8a8a7690e68bec5117b0f9ea"
metafile = true

[[files]]
file = "mods/chunkumulator.pw.toml"
hash = "82648138a721df0ac1d215037728cbd85995c8748c700eff9cb1ab1e87754b48"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "07afb1b47f10143124c5c88d76d28805cbc6bf1875eecf6bfc716d310d2205c4"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "cb16723c8c5ab522cd4bd10e200b61cebc55fc0ab7eca8d76ececcd158399650"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "54aa846a05fcea95dc57cc2ea3c37f4847c85fcaee626e6b56530628169df181"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "79d8acc0638aff455f1c12ae8e3d4c0433314e9fd3f06f8cfc7f9de7372d532e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "fcbbf01e8f9f97f3b847ff9e6ef99502e40bd32ecbf12ddc6244ebd27ee64c40"
metafile = true

[[files]]
file = "mods/planifolia.pw.toml"
hash = "b41fbdcf6b2b8844fc43fc71977c498ab8637148f6b4105cfd758b6726ac3214"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "57f3e6d029b4cac7a89934a0c055c54c54875422ae640adaea7d7db34f18942a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "47957a6bfa3bd14fc33bef6558b057b6f7c3c661416c898b5b95cbf9c038b0d7"
metafile = true

[[files]]
file = "mods/speedrunapi.pw.toml"
hash = "50337df229320fb3f736a881c2d463c3a2a17380f2c0472b8635ba4bf7fb414a"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "c3f838d63c339b8a7909b3582c08aca01b4bc5a81c0b75ff660abdfc887236bf"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "2b2cc1605abd00ec7cbf0f34c73196fce911ca5f7be6d88258e8d3f01bac5c75"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "f16bd33276dc8f4a69ddc5fc6a67368fec1f266a11b498525c6c0c00adc250a6"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "1bb5e0306d557db0ac6c72363372f15eef8cbae55c6deb96c8d9089bc5bf8c6b"
metafile = true

[[files]]
file = "mods/worldpreview.pw.toml"
hash = "73a4d6dda2a1adc81916240a51c2d402464d095334d6a747e3851b1ef207cbc7"
metafile = true
