name = "[SSG] SpeedrunPack"
author = "interp"
version = "mc1.14.4-v4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e53fcb6fc2dd4d4286c282814a4f27813bb351a4d55b11f5aa59f310122c2e1a"

[versions]
fabric = "0.16.2"
minecraft = "1.14.4"
