name = "[SSG] SpeedrunPack"
author = "interp"
version = "mc1.16.5-v4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9eed16bd2f9e2c97ab928383c13d83bc3b96c6a3d732d3a2a46a7c5d67dc217d"

[versions]
fabric = "0.16.2"
minecraft = "1.16.5"
