name = "SpeedrunPack"
author = "interp"
version = "mc1.20.1-v1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b9f2da49b139bbd2ce2a149d41eb564f3eb2f376eeef262d2524f9c7dc194f4"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
