hash-format = "sha256"

[[files]]
file = "config/mcsr/standardsettings.json"
hash = "72f4445d878e7a931b0ab48174b71b66045242904f31fa6ce0e34abb00a164ec"

[[files]]
file = "mods/antigone.pw.toml"
hash = "e24c63dd97cbcc95ccec8d639878c921cc4de3fb1b0c96db49ca5ca0ee59a0db"
metafile = true

[[files]]
file = "mods/antiresourcereload.pw.toml"
hash = "125253e67c21f331ec35a89d29da2dd2c18341638a0feb412fb30153ac66df1e"
metafile = true

[[files]]
file = "mods/atum.pw.toml"
hash = "8e8f2f30fab6a5cc33de2806060811216c09d54095c1a7c080c0f4d88783d665"
metafile = true

[[files]]
file = "mods/chunkcacher.pw.toml"
hash = "597fde2b5a9fa26f5df929cfbac401ef355cc83a477d50f8e996569f330d2ce2"
metafile = true

[[files]]
file = "mods/chunkumulator.pw.toml"
hash = "1852d91a1094bb775b575812c03e97d7cfc9634726f75bcbc501df87c7a0b2fa"
metafile = true

[[files]]
file = "mods/extra-options.pw.toml"
hash = "14ae6936a222e723d76b616d202e21b2d92f053b89a910bd3e4ef3143ad1c3a5"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "c1257a8a86ab83be8e395fd3f91edb2d94c014334ad9309301b57e035238492c"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "2eac688e042f870e808d5d9608049d43fe2420bcb4f4d41896176b0333e3a69d"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "5f734c4bb7e363951b34f145bf29b8d67616984268e00d5424823807a6806e0e"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "452081dd53baad5ab5f4b3316812723db73a30b1afd94d077d1cbb8aad13b0d6"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a36646c9af27f3d99e43184c9a6cb103ab1904849229960633037bc1e020baec"
metafile = true

[[files]]
file = "mods/seedqueue.pw.toml"
hash = "6cb0271af11f2a232bb275831f5352b4b45633abff634e6c2d8291846232c657"
metafile = true

[[files]]
file = "mods/setspawnmod.pw.toml"
hash = "a7f4c73394d42412b2f031c0a9af0e510214f3a3a6f4ec4c8c25b2ee4003130b"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "0d679a84654aadc9f2f473ec89429a12d1cad4ecf95e14fcec192d2bb22716ff"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "38c3a4a939ad384e5544c591b32c7e7dab6f13c9b479f3708e424580b3c5981d"
metafile = true

[[files]]
file = "mods/speedrunapi.pw.toml"
hash = "5045aa165b83d63aa2c891c5383162e712b5e6fadad4849140eac3f9ccaf5b15"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "e9c79d9c56ff800efd1de79d745d4d75763c9bf86a92fa14a43d7b5410c15e09"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "191e9c07fab43498aba192dad301309a56bbcd6ef73c8e5188f381dd75ba4592"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "4bad24e5dc969a800ce728417999849ee76401690cd65ee4924c75869d8392e3"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "2cced73a02dcf95b4872d13e68d1316c9ee4dae20b159c962e2c12b769cf1f02"
metafile = true

[[files]]
file = "mods/voyager.pw.toml"
hash = "eea8880c9b90e6b5339fa6a2c6c5d07ec262ddc041a96cbff81501e19875fa0c"
metafile = true
