hash-format = "sha256"

[[files]]
file = "mods/antiresourcereload.pw.toml"
hash = "02991f9f10ed7b99a478139e18b4595b696a17673dd2db1c0bb67ea0ceac57de"
metafile = true

[[files]]
file = "mods/atum.pw.toml"
hash = "7d2973017253e0314dc7971db9cf531e73399e62dc013a549f4c8e3d655a9a2f"
metafile = true

[[files]]
file = "mods/biome_threadlocal_fix.pw.toml"
hash = "26613b50a1f9ad2f5f0156a246745e245c3a672c8a8a7690e68bec5117b0f9ea"
metafile = true

[[files]]
file = "mods/chunkumulator.pw.toml"
hash = "6fd28a07956cf4a8951b80bc8c50a6ce69e74411b1152fa4aff2bb00a0d90677"
metafile = true

[[files]]
file = "mods/fabricproxy-lite.pw.toml"
hash = "91dbdcfd966b7a76072ea721de6ce403b2b9d8fa068efd2a734fcbe05df46f84"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "2adfb8850b34c722af005c1cecd79786e0892bd3df6f88c8a31f0b4bcd61e363"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "cb16723c8c5ab522cd4bd10e200b61cebc55fc0ab7eca8d76ececcd158399650"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "27030ae3896325db9de5ecc74a0693a8111ec65707c1ec75da09f2e465d6e1de"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "79d8acc0638aff455f1c12ae8e3d4c0433314e9fd3f06f8cfc7f9de7372d532e"
metafile = true

[[files]]
file = "mods/lazystronghold.pw.toml"
hash = "ca459135dd6af386fbe44a9de04346edc5cc256a88ce1b73cb437f8fbbd41b15"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "15157e4e99c5e2c10a3fe272055f2647a32324d241ff6d927aea48b618c398f8"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "60bf14d077dcfd5331d73879753ae687eec7fcbd8be00fceda78b7d4c93f6275"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "1cb3116e6de9d50efa99d44c448218c693a2668e8ca919d5f623ed786feba763"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "44e9dc6e95dd4b8f193b6cacd76c95b30abda66240a3c542ec90de028ca670b1"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "489ef4063cf28b399170a9db33770340013288dd061107763e4a949d03f9a42b"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "e6339d430f043efea68601cf9405e28c0678f08d4c90e1db532719d44b862126"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "cfec3aea6a37d116cf7d50f8c8f00e29e0a252574e9d499e5f77b9ae022cdddf"
metafile = true

[[files]]
file = "mods/voyager.pw.toml"
hash = "619642572e888cc32bd09b11bbf1dfea8240532c2847456a4300b746fc7ce8c1"
metafile = true

[[files]]
file = "mods/worldpreview.pw.toml"
hash = "a33c125f79028f6230b58855569181fe8ad13e2922c19c10323ad2fd5364ab0b"
metafile = true
