name = "SpeedrunPack"
author = "interp"
version = "mc1.16.5-v4.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "405345e43f97bbd0a1aecfb1f21d08ee390ec95af2e951d8e71ee90e8d10156d"

[versions]
fabric = "0.16.14"
minecraft = "1.16.5"
