hash-format = "sha256"

[[files]]
file = "mods/atum.pw.toml"
hash = "f3ecb5fffa4dc00cd6828819e192356ea9a46e9ec7e4298030754f0a35343be7"
metafile = true

[[files]]
file = "mods/biome_threadlocal_fix.pw.toml"
hash = "9e08a7abbc7caf5312c16223ef8a4b17cb62108908ae1bab85f5b0e072f2df7e"
metafile = true

[[files]]
file = "mods/chunkumulator.pw.toml"
hash = "82648138a721df0ac1d215037728cbd85995c8748c700eff9cb1ab1e87754b48"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "d21b6b3c584b92afb286379b9171bae2e02e814de9ac2eb87b68facf2626e881"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "2eac688e042f870e808d5d9608049d43fe2420bcb4f4d41896176b0333e3a69d"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "3a971507a82a85e1e314128bf95255925dcab5ec9cecd3ce0162e5839aa32cbf"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "452081dd53baad5ab5f4b3316812723db73a30b1afd94d077d1cbb8aad13b0d6"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "6f61b1bba38a2ddbba773f3b13d8b60e9f2f6189307670d97f8c0fd98b7347d7"
metafile = true

[[files]]
file = "mods/planifolia.pw.toml"
hash = "b41fbdcf6b2b8844fc43fc71977c498ab8637148f6b4105cfd758b6726ac3214"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "ab9cb4757b440e0d46b696938e7b87dbc33f0785c16a3e5d39e26004134b91ab"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "5d11ec8b8873655f5b0e20bee47982805365670c3346ae6b1d2cdec657f04a16"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "95e8659a7a19029187e53cc71f03fa1b8805b2c398c7132b261ea0f902768e7d"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "c448747cf140f1db20e0abf522d14b22665649b99ae3ff050fb3a4401bda8728"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "487893853b4c5c0151d5e674d1ac581a0f558416aa58d2e05f1e17d7cf9bc841"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "ed292916a47446d819cb1092b00cf6ff87fdcb062b70e8ba0d9cd8810d8c7bc9"
metafile = true
