hash-format = "sha256"

[[files]]
file = "mods/atum.pw.toml"
hash = "f3ecb5fffa4dc00cd6828819e192356ea9a46e9ec7e4298030754f0a35343be7"
metafile = true

[[files]]
file = "mods/biome_threadlocal_fix.pw.toml"
hash = "26613b50a1f9ad2f5f0156a246745e245c3a672c8a8a7690e68bec5117b0f9ea"
metafile = true

[[files]]
file = "mods/chunkumulator.pw.toml"
hash = "82648138a721df0ac1d215037728cbd85995c8748c700eff9cb1ab1e87754b48"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "c1f30220e9c9fac2aa10f85a9465513161a9a42c8aa3ed9d4539456e55d9af84"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "6cc90abc16b944bcc2f3061bca312de0119ac4a550a4b2f1fbd2a097aa5318a2"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "54aa846a05fcea95dc57cc2ea3c37f4847c85fcaee626e6b56530628169df181"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "79d8acc0638aff455f1c12ae8e3d4c0433314e9fd3f06f8cfc7f9de7372d532e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "fcbbf01e8f9f97f3b847ff9e6ef99502e40bd32ecbf12ddc6244ebd27ee64c40"
metafile = true

[[files]]
file = "mods/planifolia.pw.toml"
hash = "b41fbdcf6b2b8844fc43fc71977c498ab8637148f6b4105cfd758b6726ac3214"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "57f3e6d029b4cac7a89934a0c055c54c54875422ae640adaea7d7db34f18942a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "47957a6bfa3bd14fc33bef6558b057b6f7c3c661416c898b5b95cbf9c038b0d7"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "c3f838d63c339b8a7909b3582c08aca01b4bc5a81c0b75ff660abdfc887236bf"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "87ce9a9c694790892840e1d932a57428dee57e75f6e1bd1be3a2bb639f3c78f5"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "f16bd33276dc8f4a69ddc5fc6a67368fec1f266a11b498525c6c0c00adc250a6"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "6150c697e8a2eae5016a74ed6b5f0cfad5f8b476d18eb4aaea2fa863001eedef"
metafile = true
