name = "SpeedrunPack"
author = "interp"
version = "mc1.19.4-v3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62bc9594e80d6368f96f4e77fd5f2c19798673eef1c5abd8b1d531f883b75691"

[versions]
fabric = "0.15.11"
minecraft = "1.19.4"
