hash-format = "sha256"

[[files]]
file = "mods/antiresourcereload.pw.toml"
hash = "f8f6f41ef8f3ef41c75d84bbb02cc81c686d84f1a45e0f11051c2a6e05efaba7"
metafile = true

[[files]]
file = "mods/atum.pw.toml"
hash = "5933fe812f53fefa8313b332c929e79b64ea4d6dfb653901af7397f57c949b3e"
metafile = true

[[files]]
file = "mods/biome_threadlocal_fix.pw.toml"
hash = "beab203770a27295c5210cb2390691db6cac03c0c7d95da141b7cc306b4d9952"
metafile = true

[[files]]
file = "mods/chunkumulator.pw.toml"
hash = "0214ad1dc747b891912bbb4ed4c6fbd5b0c4e66c9ee55406400c239ca6c7312a"
metafile = true

[[files]]
file = "mods/fabricproxy-lite.pw.toml"
hash = "f082bbb9f0b3275e6c39ec352a247a5ea7109e977c8f189432561d48b34d63d1"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "d38137291d3d8b66e33330574d5703ff77d77e77d0479c3d0063c16ae61ff65d"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "cb16723c8c5ab522cd4bd10e200b61cebc55fc0ab7eca8d76ececcd158399650"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "a6332c5ca6415fd716cc5dcdb5cdbae76e95691b0ab88b4ceb2fe41073567a78"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "79d8acc0638aff455f1c12ae8e3d4c0433314e9fd3f06f8cfc7f9de7372d532e"
metafile = true

[[files]]
file = "mods/lazystronghold.pw.toml"
hash = "c485e3c58f8fabd92baa7c4505761d71496fbc3a8a5bb59885c80b1349cc00b1"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b5674f4b913e94a02f3495a9034a076368ffe403425c12a6528553ea15330877"
metafile = true

[[files]]
file = "mods/planifolia.pw.toml"
hash = "3f09a327c893a4a71b303d4d2801721bcc181356928bcf48fbcc9f56f31c1467"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "e7313254c5c648dacda72051cc0df80dafa7a578ba8f726d93a77ab24670a103"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "74acaca011b15f987e9986d8a521b0d72eb6eea3dd2917cd7ac0c148c73499b8"
metafile = true

[[files]]
file = "mods/speedrunapi.pw.toml"
hash = "50337df229320fb3f736a881c2d463c3a2a17380f2c0472b8635ba4bf7fb414a"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "3448283763ec94d8201a309652500180977258942bf6c554e0adc8faa17023d9"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "5a6a15cce7261196476b52b10aff2e2f0855971869606b51f4f78741ce01bd8c"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "766ea262e60e7ea5a6b5ab2641384dd330c9487f4939d59276c1e8cce57b279c"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "cfec3aea6a37d116cf7d50f8c8f00e29e0a252574e9d499e5f77b9ae022cdddf"
metafile = true

[[files]]
file = "mods/worldpreview.pw.toml"
hash = "c8cadf8931aa071c08648dc56de62550b775e7f9e74d9ea69c618082c1a9a7b4"
metafile = true
