name = "SpeedrunPack"
author = "interp"
version = "mc1.17-v1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98f84d646a07833066614a2ce0b3fa847c1fa5d309fabe80d4349ca0b0eda2e0"

[versions]
fabric = "0.18.4"
minecraft = "1.17"
