name = "SpeedrunPack"
author = "interp"
version = "mc1.19.2-v5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be56f385fff342649541ad80f0550d228e8a921ebd28767c775680400ead436a"

[versions]
fabric = "0.18.4"
minecraft = "1.19.2"
