hash-format = "sha256"

[[files]]
file = "mods/atum.pw.toml"
hash = "de299a0bff534a0b26210a943e07c97e32c395aed31b0374e63b79c0c5c2275b"
metafile = true

[[files]]
file = "mods/biome_threadlocal_fix.pw.toml"
hash = "6926c463a441251ce509124060049767324b9373517474e99e0166ae8aacdf23"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "c70108e0a1bda192f096e4c163990481a9f95bb40d7678f8e53085f6dc7168e6"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "b32ab36c783ea2006118f9600a79be2b87d07945e1105f7df273ac5a3b913d8a"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "6584867f334f838cd2b01e1a897f90ac4b652ab5996f10b7ab1c5163be35a361"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "560dbe8638353439c1dd336db9d1d1fffed5e192c2ffa025da7a063592fcfaf9"
metafile = true

[[files]]
file = "mods/planifolia.pw.toml"
hash = "ab388d94e80ecc232168219cbd5ed4d9297ee2d568ff85efc9d323ebdaea1e8b"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "01c9b73ac3598913867d392af6f09cc7477385c73889f59ca0bf24ae7fee8a44"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "0d104a45139a6144a20804340e4e38ea5d3d6e7768c145158d123112ac1b1a8c"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "5f6e872cef81bce05987d884f396c0f18980c03d1f44445eaa8af8f8ff0413a7"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "1cfcd288d93bb8763070489fc70597a6cabfa196e7147d8c596fb6b07953529e"
metafile = true
