name = "SpeedrunPack"
author = "interp"
version = "mc1.21.10-v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be33c507e77003b1954ec5a228c4665c1cec22565c0deaea30f5ca0d538fc0ce"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
