hash-format = "sha256"

[[files]]
file = "mods/antiresourcereload.pw.toml"
hash = "9f81341cfc8bd44dd0004667fd8d7e6d90ba9a8f03514309e518d2e2617489f3"
metafile = true

[[files]]
file = "mods/atum.pw.toml"
hash = "be77b9bc6dda95adbe17b5b728f7c884164eed88f3d668d8a141c5937eb18f4c"
metafile = true

[[files]]
file = "mods/chunkumulator.pw.toml"
hash = "9411b209ba775edc1d83d2d2c0c86954530ce5205d0ae37ad16f22bb1de69492"
metafile = true

[[files]]
file = "mods/extra-options.pw.toml"
hash = "ba1400190f90fc1c0d987ffc808916a985fe48250d9b54b1b85bdd6d75d75677"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "94a4f01de3df14f1de2f663abfa6cff04072dbf9cedeb5906b6d6ad85bb364ac"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "cb16723c8c5ab522cd4bd10e200b61cebc55fc0ab7eca8d76ececcd158399650"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "e6c277a4954ea0867e72cda1fc6cd41b53d260f457f808be74f186efd999b0c7"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "79d8acc0638aff455f1c12ae8e3d4c0433314e9fd3f06f8cfc7f9de7372d532e"
metafile = true

[[files]]
file = "mods/lazystronghold.pw.toml"
hash = "a77a408788a4bf71ae062de731738123ef89b3bb862c2524a735d92da229283c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "696cfc74f200764849cda663fcdfc45ed585042cf38a12dd0d488b878a8ff4f1"
metafile = true

[[files]]
file = "mods/seedqueue.pw.toml"
hash = "9570c59d26d12ae4f04edd57ea80e25fff5dea69cef9626f00cb9749d1a28f4a"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "2bc31d31bfd4a15a6e9c1ae1b2f00db1c425a16369e9cce70f85ca9e6ad9d2da"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "6118813e72525f18cc58e3089feb78f17d43d7fbc5d490027ae68eb91e3350fc"
metafile = true

[[files]]
file = "mods/speedrunapi.pw.toml"
hash = "9a7f6b1dc1e6fa4ffb6e4c306f264d62d2d354125c2beb2b0eeff95244295647"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "afc2b2bb373a26c9afd38beb9a6b08e13f53d9021297136ca23b62bfd3c82a25"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "4c6d0fd87267e4b860ae4460ecb8cb430bc824517ed8a94b51de11c0d98e94e1"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "bd8aa93be9da92b4d652661655aa6e6f3812d709b30395a158c3f4797520da32"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "01801d8f2e565f06b540e9f4d86e61a1112fe9e320dd848301f2dfa9138efe88"
metafile = true

[[files]]
file = "mods/voyager.pw.toml"
hash = "619642572e888cc32bd09b11bbf1dfea8240532c2847456a4300b746fc7ce8c1"
metafile = true

[[files]]
file = "mods/worldpreview.pw.toml"
hash = "9d2295d6ae3a2a118ad07d92fe1adbb61cc2bfe2b490e3dbc37091c0e160454d"
metafile = true
