hash-format = "sha256"

[[files]]
file = "mods/antiresourcereload.pw.toml"
hash = "7a2e008910707d3257960b7167351c696c9df507416551d2c0f0ab24292162ac"
metafile = true

[[files]]
file = "mods/atum.pw.toml"
hash = "b233266793c3a8e3a24658f45d427e344f4dae7834dd3bd315b9daa85168b06f"
metafile = true

[[files]]
file = "mods/chunkumulator.pw.toml"
hash = "9411b209ba775edc1d83d2d2c0c86954530ce5205d0ae37ad16f22bb1de69492"
metafile = true

[[files]]
file = "mods/extra-options.pw.toml"
hash = "d34c21f035b5c8759cfb78f49ad99d12d01727494412836dfcf5cdfab224fa3c"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "a568dd176f01497a639851d49ea77f4801cda6d340a44c18b1c7e6fc8c718c91"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "6cc90abc16b944bcc2f3061bca312de0119ac4a550a4b2f1fbd2a097aa5318a2"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "e6c277a4954ea0867e72cda1fc6cd41b53d260f457f808be74f186efd999b0c7"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "79d8acc0638aff455f1c12ae8e3d4c0433314e9fd3f06f8cfc7f9de7372d532e"
metafile = true

[[files]]
file = "mods/lazystronghold.pw.toml"
hash = "a77a408788a4bf71ae062de731738123ef89b3bb862c2524a735d92da229283c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "696cfc74f200764849cda663fcdfc45ed585042cf38a12dd0d488b878a8ff4f1"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "a5f13466014f2cbf04c035d87fb48e9bc7bfb920d05ff47faa03dcb986631985"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "26594beb645c754e6d736929e67804d7bcb85cbf77a70a32331ca678e6d410be"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "afc2b2bb373a26c9afd38beb9a6b08e13f53d9021297136ca23b62bfd3c82a25"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "a92a5c7ea90a7340d0414214dcbd0e5d6eb515233768a26a6eec405ae50e42f7"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "5c76f1f40159d1e98ac94a40e2e700d1ec2ce0390912fcbba067874246759c08"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "01801d8f2e565f06b540e9f4d86e61a1112fe9e320dd848301f2dfa9138efe88"
metafile = true

[[files]]
file = "mods/voyager.pw.toml"
hash = "619642572e888cc32bd09b11bbf1dfea8240532c2847456a4300b746fc7ce8c1"
metafile = true

[[files]]
file = "mods/worldpreview.pw.toml"
hash = "d26744a7ccb7553369cbe5d2c17803bbd173d6043a6b87040333c03055dea118"
metafile = true
