name = "SpeedrunPack"
author = "interp"
version = "mc1.15.2-v4.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5284ed6672c5954752a1503da9e50863c2480c6fd739416af624f0cf320c37f"

[versions]
fabric = "0.16.14"
minecraft = "1.15.2"
