name = "SpeedrunPack"
author = "interp"
version = "mc1.15.2-v4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fd706538997d1ca1db9846b4fa3c8d0d083226d041e9b4919c759d397797a3c"

[versions]
fabric = "0.16.2"
minecraft = "1.15.2"
