hash-format = "sha256"

[[files]]
file = "mods/antiresourcereload.pw.toml"
hash = "d36c38da7fbff8ce2d1434e3f669c8bf69351d50d13b6a2bf78017de3b6fa8e2"
metafile = true

[[files]]
file = "mods/atum.pw.toml"
hash = "83f96431d71ef920df8a71fe7706d2ff4da120a2bdec4936ab87657802311992"
metafile = true

[[files]]
file = "mods/biome_threadlocal_fix.pw.toml"
hash = "26613b50a1f9ad2f5f0156a246745e245c3a672c8a8a7690e68bec5117b0f9ea"
metafile = true

[[files]]
file = "mods/chunkumulator.pw.toml"
hash = "82648138a721df0ac1d215037728cbd85995c8748c700eff9cb1ab1e87754b48"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "c30d6052fd363dc90eb288fc08f4e44a0a22598f1b8bc1092dcba1b1b47a819a"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "cb16723c8c5ab522cd4bd10e200b61cebc55fc0ab7eca8d76ececcd158399650"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "54aa846a05fcea95dc57cc2ea3c37f4847c85fcaee626e6b56530628169df181"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "79d8acc0638aff455f1c12ae8e3d4c0433314e9fd3f06f8cfc7f9de7372d532e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "d0f503bc36e8fba8ece84b17b43c7d2740d2908ae66e44f4ed1b3d85e45f1aca"
metafile = true

[[files]]
file = "mods/planifolia.pw.toml"
hash = "b41fbdcf6b2b8844fc43fc71977c498ab8637148f6b4105cfd758b6726ac3214"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "60bf14d077dcfd5331d73879753ae687eec7fcbd8be00fceda78b7d4c93f6275"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "20514334c60c97e6ddbd4ec90c63a097cbb4fd829825e57e7d446b41451f86db"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "f638259568bc7d303ebe298dd84703c09303ae739067a49325d8744a5f8745ab"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "87ce9a9c694790892840e1d932a57428dee57e75f6e1bd1be3a2bb639f3c78f5"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "dc533ea623f8e12d17801aa23dd6dfcbf2294cfac455a5bf4b916de27ff7d24e"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "cfec3aea6a37d116cf7d50f8c8f00e29e0a252574e9d499e5f77b9ae022cdddf"
metafile = true
