name = "SpeedrunPack"
author = "interp"
version = "mc1.18.1-v4.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3430c1a2a3289d96f4b86064ae9a9eb769dde60d4b4d314ffed84c852c7f35a0"

[versions]
fabric = "0.17.2"
minecraft = "1.18.1"
