name = "SpeedrunPack"
author = "interp"
version = "mc1.21.7-v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89f10102b6529ca499e0520b6bf1ddb9f5d96d2ac7836d0d59a34d2f0793eff6"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
