hash-format = "sha256"

[[files]]
file = "mods/atum.pw.toml"
hash = "1f2ac191004e7f9264c9be8df3147589cb2ea27ec12b61f88f1a17b25b0a15fc"
metafile = true

[[files]]
file = "mods/biome_threadlocal_fix.pw.toml"
hash = "9fb58a8e8b2de2cab99dc42c081e2e7430d7811f1541ce73ae4055cb10910fad"
metafile = true

[[files]]
file = "mods/fabricproxy-lite.pw.toml"
hash = "f9286b56143a6379ce798304766dec018bb6e411f31ba27a459eb3fbf86ce1af"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "40cb48ca154749289fbc0b36be48879cfe53c6307276e0331f175bcd27a10e8a"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "c92202f81e861f3a5b230f8af2d1156df2e45a6b5ad424d3c5240cbc0d0cfc87"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "d7a58a8ec43438e53eb25258c3489b29fa9727a5f931f256ecb2e67c742e1b8d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "313089d08ee84b66c30e0c088f0f47304a8f12c873cc90281fb6522e36363379"
metafile = true

[[files]]
file = "mods/planifolia.pw.toml"
hash = "790b5624bc28068b02b0b04025097aab4e7ace8f8fe7466b8515ee682f5b625e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "2f9b85915042b847ebacc1dc70ee3d130a546b404d5ca428124ba0b1bf72d062"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "d5f4edb52a25c59a11ff777251ffdc0ec90672483b733d35a47eab053e68551b"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "0141f9ba94c8fd65b7fe02908221d1385c874dd28ecf0ee37daf3cb402ba799e"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "6150c697e8a2eae5016a74ed6b5f0cfad5f8b476d18eb4aaea2fa863001eedef"
metafile = true
