hash-format = "sha256"

[[files]]
file = "mods/atum.pw.toml"
hash = "d7011e17c786aea74da4d6a9750d9b62b1c7f7e6af034ea69776e4719f9c9f01"
metafile = true

[[files]]
file = "mods/biome_threadlocal_fix.pw.toml"
hash = "26613b50a1f9ad2f5f0156a246745e245c3a672c8a8a7690e68bec5117b0f9ea"
metafile = true

[[files]]
file = "mods/chunkumulator.pw.toml"
hash = "341759782a55dea85e5a0e2233a39f2020028f3b62c32f822d0c5c900b3b839d"
metafile = true

[[files]]
file = "mods/fabricproxy-lite.pw.toml"
hash = "2ac2e64d93911008542eca462d9a8995f33d9608be00ca7d86bb5489f600d1e1"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "bcf6bea79bbd1ab0dd4102b9b8fecfdc97d252378d7795c4840416455b4c319a"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "cb16723c8c5ab522cd4bd10e200b61cebc55fc0ab7eca8d76ececcd158399650"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "cfb5282e3cc8e4c2a74e59334c74ffd314e1180220cd46d21dc88fb517cf6a14"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "8ad696a44b9659bd907d7b5e49e409b59990f991e3fb5534fde31d861250c9e0"
metafile = true

[[files]]
file = "mods/planifolia.pw.toml"
hash = "1a27fe495b6768f58953d3bfc82434be17449cfe875fa5fcb18fb57ee9e17928"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "57f3e6d029b4cac7a89934a0c055c54c54875422ae640adaea7d7db34f18942a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "a10f8d11ef6498ea50943f7b64795e8d0a2581777bc43279d809684839652c6a"
metafile = true

[[files]]
file = "mods/speedrunapi.pw.toml"
hash = "c5dd3ef897c13e163d4770d4b7d3387496e0141fc0bac79c541e0b6f7c25b4a5"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "706ea9d09676b4420990e3a591a98718104e4e7a2dca1b2d40e0fdae3b852659"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "51ecebda7ca161cb1698f26771261bdaea3f1cb9fef48d1e21c4e3f007213275"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "bf641be7b695d6f04cfad96b8fa9704ca13e1e35857e30470a0882dc3bf1566b"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "1bb5e0306d557db0ac6c72363372f15eef8cbae55c6deb96c8d9089bc5bf8c6b"
metafile = true

[[files]]
file = "mods/worldpreview.pw.toml"
hash = "f8a90eff2f5d1a420491f0881e76d1dd1f6fa681b606b394c62677bc7a2e1a76"
metafile = true
