hash-format = "sha256"

[[files]]
file = "mods/atum.pw.toml"
hash = "ba4dc05d31f5a39f20694db215cc325e38309e9d3341be9663bb5467cc08b073"
metafile = true

[[files]]
file = "mods/biome_threadlocal_fix.pw.toml"
hash = "9e08a7abbc7caf5312c16223ef8a4b17cb62108908ae1bab85f5b0e072f2df7e"
metafile = true

[[files]]
file = "mods/chunkumulator.pw.toml"
hash = "341759782a55dea85e5a0e2233a39f2020028f3b62c32f822d0c5c900b3b839d"
metafile = true

[[files]]
file = "mods/fabricproxy-lite.pw.toml"
hash = "e1ad34dad8fbc115cff91e48ff31e548fa1f2a93faa8d54bd2ceb2483bc77473"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "b586f38e8c822e719cfdaa274bb9520d8dfbe25742386dd9e4424f04b98577f4"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "2eac688e042f870e808d5d9608049d43fe2420bcb4f4d41896176b0333e3a69d"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "768c00403b8505a6dfc7a6487c2d0f593e297d33cf6181e28c00117324fe63a5"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b7c5e3963896c3cdb78e36c5b08f9ac39465d22723dcfa31dbe5e8fd7fb79e41"
metafile = true

[[files]]
file = "mods/planifolia.pw.toml"
hash = "1a27fe495b6768f58953d3bfc82434be17449cfe875fa5fcb18fb57ee9e17928"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "ab9cb4757b440e0d46b696938e7b87dbc33f0785c16a3e5d39e26004134b91ab"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "5688d9b285e0cba14fb51760de9e51ba6411e1c07f162c82035d4b23c60d1f0c"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "aa0af914bab2eea76b23eb031d6e7d0f47a0f31a707200862abdf4ec370b7c64"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "293eda8e7f453b825e59a751259a10c5549b94b1e67b0bd3e138e3bf38b0cbd3"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "f3b65c72ceb60f7c0d9783873e8f8e02e85e560f594cafbe09bbbc71f89d6739"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "ed292916a47446d819cb1092b00cf6ff87fdcb062b70e8ba0d9cd8810d8c7bc9"
metafile = true
