name = "SpeedrunPack"
author = "interp"
version = "mc1.19.4-v4.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a135c3fab18c78d1d66d6bbbd9cf50ff60c2d0eb1a449720bfdb519b73bcefcd"

[versions]
fabric = "0.16.14"
minecraft = "1.19.4"
