hash-format = "sha256"

[[files]]
file = "mods/antigone.pw.toml"
hash = "1564987d2bc06413df772cc697f62468b431df2abb8f62820afa27f9835abbf2"
metafile = true

[[files]]
file = "mods/antiresourcereload.pw.toml"
hash = "3fb3ca0687f686447863c477d974bca02ca006c35a5b7a5ac6ec3741a9eab7a5"
metafile = true

[[files]]
file = "mods/atum.pw.toml"
hash = "321a04fe3deddeaaf62c70c842ad346a0d1499abee8ec71c13a194ce1816f939"
metafile = true

[[files]]
file = "mods/chunkumulator.pw.toml"
hash = "fa7d6b9bac33982f4ea539f93a4ee5f1cf458ae3171fe83a1e4e2da62b1137ef"
metafile = true

[[files]]
file = "mods/extra-options.pw.toml"
hash = "1fa0fc693e3ec1aabebd1f0a577528f137a4e5b5dcb25759cf532f6801c039f5"
metafile = true

[[files]]
file = "mods/fast_reset.pw.toml"
hash = "67c3f3890ebafb72a1935d0839777a41abc3ea4933f3df03df3d3d27846b75f7"
metafile = true

[[files]]
file = "mods/forceport.pw.toml"
hash = "7b2b81d7fda9b58e2f9f44bd310ded258352739b7941ebf99b5ea3574e46279d"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "fd81ba13376b629587431fe33961e0cbb37c894babc81a104ee773386a2d6395"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "0eee88e10ef67ad2bd5d9a38f8e5e050f12514b0f80c23bce5bcf7f7066edcdd"
metafile = true

[[files]]
file = "mods/lazystronghold.pw.toml"
hash = "8d2deb782b104ef7481e2fd06ff5cc06108ed1367d62d8bd13baff63b4877d4b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0a371ac57198a2095c6ea84adbd741cff73a94f5e27119a58aa20e81b293e6c1"
metafile = true

[[files]]
file = "mods/seedqueue.pw.toml"
hash = "0a38b0cc3739b3e721884da54ee493953a3877efd933fbcd0b0cd126e19efc13"
metafile = true

[[files]]
file = "mods/sleepbackground.pw.toml"
hash = "2b7f2518a7decbe2d6ac91d1232955980a4704c3d4df98d24f69dd0f407e3a22"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "684f3af2b934cdf329efd48f345a301648a635c320409bb14f907a9a1e12ca4d"
metafile = true

[[files]]
file = "mods/speedrunapi.pw.toml"
hash = "4a177cb89ddf80bff3b6b09bc4a0d18247dcc85a487bd230a7d4654a9b7ccc52"
metafile = true

[[files]]
file = "mods/speedrunigt.pw.toml"
hash = "3f2af522dc9e103af4c00228c478fa9a3be5c9d117389a82ce410a0fe943302f"
metafile = true

[[files]]
file = "mods/standardsettings.pw.toml"
hash = "8748ebf5899ad42ae625aac8cbc8bd396910c26008346552d30554232312fe76"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "71624976a3942298dc16e30aa2e6c6387c926b2e4227ceb41208ce9a2bd84d01"
metafile = true

[[files]]
file = "mods/state-output.pw.toml"
hash = "cfec3aea6a37d116cf7d50f8c8f00e29e0a252574e9d499e5f77b9ae022cdddf"
metafile = true

[[files]]
file = "mods/voyager.pw.toml"
hash = "dcd673cde784bf7d2d093207e9ca28b817f1436b3a90d1e80d134462580e167f"
metafile = true

[[files]]
file = "mods/worldpreview.pw.toml"
hash = "46df921231b67e7f9e3a4d6abc2cf665459b0e4cb5ffef2f9df7cc3c67cf52f0"
metafile = true
